matrix:
  include:
  - language: php
    php:
      - '7.1'
    before_script:
      - cd ui
      - composer install --dev
      - cp env.travis .env
      - php artisan key:generate
    script: vendor/bin/phpunit && vendor/bin/phpcs

  - language: ptyhon
    sudo: true
    python:
      - "3.5"
      - "3.6"
    before_install:
      - sudo apt-get update
    insatll:
      - pip install scapy-python3
      - pip install requests
      - pip install PyMySQL
    before_script:
      - cd python
    script:
      - python3 --version
      - python3 tu_basics.py
      - sudo python3 tu_allsnifferprocess.py
notifications:
    slack: cylab-be:SgDUjbNn00DSxqr5h20OG5Hs
