language: php
php:
  - '7.1'
before_script:
  - cd ui
  - composer install --dev
  - cp env.travis .env
  - php artisan key:generate
script: vendor/bin/phpunit && vendor/bin/phpcs
notifications:
    slack: cylab-be:SgDUjbNn00DSxqr5h20OG5Hs
