matrix:
  include:
  - language: php
    php:
      - '7.1'
    before_script:
      - cd ui
      - composer install --dev
      - cp env.travis .env
      - php artisan key:generate
    script: vendor/bin/phpunit && vendor/bin/phpcs

  - language: ptyhon
    sudo: true
    python:
      - "3.5"
      - "3.6"
    before_install:
      - echo 'deb http://us.archive.ubuntu.com/ubuntu/ xenial main restricted' > /etc/apt/sources
      - echo 'deb http://us.archive.ubuntu.com/ubuntu/ xenial-updates main restricted' >> /etc/apt/sources
      - echo 'deb http://us.archive.ubuntu.com/ubuntu/ xenial universe' >> /etc/apt/sources
      - echo 'deb http://us.archive.ubuntu.com/ubuntu/ xenial-updates universe' >> /etc/apt/sources
      - echo 'deb http://us.archive.ubuntu.com/ubuntu/ xenial multiverse' >> /etc/apt/sources
      - echo 'deb http://us.archive.ubuntu.com/ubuntu/ xenial-updates multiverse' >> /etc/apt/sources
      - echo 'deb http://us.archive.ubuntu.com/ubuntu/ xenial-backports main restricted universe multiverse' >> /etc/apt/sources
      - echo 'deb http://security.ubuntu.com/ubuntu xenial-security main restricted' >> /etc/apt/sources
      - echo 'deb http://security.ubuntu.com/ubuntu xenial-security universe' >> /etc/apt/sources
      - echo 'deb http://security.ubuntu.com/ubuntu xenial-security multiverse' >> /etc/apt/sources
      - sudo apt-get update
      - sudo apt-get install python3-pymysql
    insatll:
      - pip install scapy-python3
      - pip install requests
      - pip install PyMySQL
      - pip install requests
    before_script:
      - cd python
      - export $TRAVIS_PYTHON_VERSION='3.6'
    script:
      - python --version
      - python tu_basics.py
      - sudo python tu_allsnifferprocess.py
notifications:
    slack: cylab-be:SgDUjbNn00DSxqr5h20OG5Hs
